name: Daily Timetable

on:
  schedule:
    # 07:00 KST on weekdays => 22:00 UTC on SUN-THU
    - cron: '0 22 * * SUN-THU'
  workflow_dispatch:
    inputs:
      test_mode:
        description: 'Run in test mode (no real Instagram post)'
        required: true
        default: 'true'
        type: choice
        options: ['true', 'false']

permissions:
  contents: read

jobs:
  run-daily:
    concurrency:
      group: insta-timetable-${{ github.ref_name }}
      cancel-in-progress: false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Restore state cache (token/hash)
        id: state_cache
        uses: actions/cache/restore@v4
        with:
          path: state
          key: state-${{ github.ref_name }}-${{ github.run_id }}-${{ github.run_attempt }}
          restore-keys: |
            state-${{ github.ref_name }}-
            state-
      - name: Check weekday (KST)
        id: weekday
        run: |
          dow=$(TZ=Asia/Seoul date +%u)
          if [ "$dow" -ge 6 ]; then
            echo "skip=true" >> $GITHUB_OUTPUT
            echo "Weekend (KST). Skipping job."
          else
            echo "skip=false" >> $GITHUB_OUTPUT
          fi

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
        if: ${{ steps.weekday.outputs.skip != 'true' }}

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
        if: ${{ steps.weekday.outputs.skip != 'true' }}

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        if: ${{ steps.weekday.outputs.skip != 'true' }}

      - name: Run daily job (render + upload/test)
        env:
          # Required
          NEIS_KEY: ${{ secrets.NEIS_KEY }}
          # Instagram (set on Secrets; POST_TEST_MODE controls real post or not)
          IG_PAGE_ACCESS_TOKEN: ${{ secrets.IG_PAGE_ACCESS_TOKEN }}
          IG_BUSINESS_ID: ${{ secrets.IG_BUSINESS_ID }}
          FB_APP_SECRET: ${{ secrets.FB_APP_SECRET }}
          FB_APP_ID: ${{ secrets.FB_APP_ID }}

          # App config (safe defaults; override with repo Variables or Secrets)
          TIMEZONE: Asia/Seoul
          SCHOOL_NAME: ${{ vars.SCHOOL_NAME || '선린인터넷고등학교' }}
          SCHOOL_LEVEL: ${{ vars.SCHOOL_LEVEL || 'his' }}
          GRADE: ${{ vars.GRADE || '3' }}
          CLASS_NM: ${{ vars.CLASS_NM || '11' }}
          BRAND_COLOR_HEX: ${{ vars.BRAND_COLOR_HEX || '#2A6CF0' }}

          # Posting mode: default true unless manually overridden
          POST_TEST_MODE: ${{ inputs.test_mode || 'true' }}

          # Optional: date/subject placement can be tuned via repo Variables
          DATE_ANCHOR_XY: ${{ vars.DATE_ANCHOR_XY }}
          DATE_ANCHOR_MODE: ${{ vars.DATE_ANCHOR_MODE }}
          DATE_ALIGN: ${{ vars.DATE_ALIGN }}
          DATE_ALIGN_X1: ${{ vars.DATE_ALIGN_X1 }}

          SUBJECT_ANCHOR_XY: ${{ vars.SUBJECT_ANCHOR_XY }}
          SUBJECT_ANCHOR_MODE: ${{ vars.SUBJECT_ANCHOR_MODE }}
          SUBJECT_ROW_DY: ${{ vars.SUBJECT_ROW_DY }}
          SUBJECT_ALIGN: ${{ vars.SUBJECT_ALIGN }}
          SUBJECT_ALIGN_X1: ${{ vars.SUBJECT_ALIGN_X1 }}
          SUBJECT_ANCHOR_AFTER_LUNCH_XY: ${{ vars.SUBJECT_ANCHOR_AFTER_LUNCH_XY }}
          SUBJECT_ANCHOR_AFTER_LUNCH_XY_7TIME: ${{ vars.SUBJECT_ANCHOR_AFTER_LUNCH_XY_7TIME }}
          SUBJECT_ROW_DY_AFTER_LUNCH: ${{ vars.SUBJECT_ROW_DY_AFTER_LUNCH }}

        run: |
          python -m src.daemon --run-now
        if: ${{ steps.weekday.outputs.skip != 'true' }}

      - name: Save state cache
        # Save after running; ensures update workflow can restore today's hash
        if: ${{ always() && steps.weekday.outputs.skip != 'true' && steps.state_cache.outputs.cache-hit != 'true' }}
        continue-on-error: true
        uses: actions/cache/save@v4
        with:
          path: state
          key: state-${{ github.ref_name }}-${{ github.run_id }}-${{ github.run_attempt }}

      - name: Upload image artifact
        uses: actions/upload-artifact@v4
        with:
          name: timetable-image
          path: out/*.jpg
          if-no-files-found: ignore
        if: ${{ steps.weekday.outputs.skip != 'true' }}
