name: Update Timetable (Weekdays 07:00–12:00 KST)

on:
  schedule:
    # Exactly 07:00–12:00 KST on weekdays (UTC is -9h)
    - cron: '0,30 22-23 * * MON-FRI'  # 07:00–08:30 KST
    - cron: '0,30 0-2 * * MON-FRI'    # 09:00–11:30 KST
    - cron: '0 3 * * MON-FRI'         # 12:00 KST
  workflow_dispatch:
    inputs:
      test_mode:
        description: 'Run in test mode (no real Instagram post)'
        required: true
        default: 'true'
        type: choice
        options: ['true', 'false']

permissions:
  contents: read

concurrency:
  group: insta-timetable-${{ github.ref_name }}
  cancel-in-progress: false

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check weekday (KST)
        id: weekday
        run: |
          dow=$(TZ=Asia/Seoul date +%u)
          if [ "$dow" -ge 6 ]; then
            echo "skip=true" >> $GITHUB_OUTPUT
            echo "Weekend (KST). Skipping job."
          else
            echo "skip=false" >> $GITHUB_OUTPUT
          fi

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
        if: ${{ steps.weekday.outputs.skip != 'true' }}

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
        if: ${{ steps.weekday.outputs.skip != 'true' }}

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        if: ${{ steps.weekday.outputs.skip != 'true' }}

      - name: Preflight env
        run: |
          python - << 'PY'
          import os, sys
          has_fixed_full = all(bool(os.getenv(k)) for k in ['IG_PAGE_ACCESS_TOKEN','IG_BUSINESS_ID'])
          has_fixed_partial = all(bool(os.getenv(k)) for k in ['IG_PAGE_ACCESS_TOKEN','PAGE_ID'])
          has_auto  = all(bool(os.getenv(k)) for k in ['IG_USER_ACCESS_TOKEN','PAGE_ID'])
          if not bool(os.getenv('NEIS_KEY')):
              print('Missing NEIS_KEY')
              sys.exit(1)
          if not (has_fixed_full or has_fixed_partial or has_auto):
              print('Provide one of:')
              print('- Fixed: IG_PAGE_ACCESS_TOKEN + IG_BUSINESS_ID')
              print('- Fixed (derive IG id): IG_PAGE_ACCESS_TOKEN + PAGE_ID')
              print('- Auto: IG_USER_ACCESS_TOKEN + PAGE_ID (+ FB_APP_ID/FB_APP_SECRET)')
              sys.exit(1)
          print('Preflight OK')
          PY
        env:
          NEIS_KEY: ${{ secrets.NEIS_KEY || vars.NEIS_KEY }}
          IG_PAGE_ACCESS_TOKEN: ${{ secrets.IG_PAGE_ACCESS_TOKEN }}
          IG_BUSINESS_ID: ${{ secrets.IG_BUSINESS_ID }}
          IG_USER_ACCESS_TOKEN: ${{ secrets.IG_USER_ACCESS_TOKEN }}
          PAGE_ID: ${{ secrets.PAGE_ID }}
          FB_APP_ID: ${{ secrets.FB_APP_ID }}
          FB_APP_SECRET: ${{ secrets.FB_APP_SECRET }}
        if: ${{ steps.weekday.outputs.skip != 'true' }}

      - name: Restore state cache (token/hash)
        id: state_cache
        uses: actions/cache/restore@v4
        with:
          path: state
          key: state-${{ github.ref_name }}-${{ github.run_id }}-${{ github.run_attempt }}
          restore-keys: |
            state-${{ github.ref_name }}-
            state-
        if: ${{ steps.weekday.outputs.skip != 'true' }}

      - name: Run update job (render + upload/test)
        env:
          # Required
          NEIS_KEY: ${{ secrets.NEIS_KEY }}
          # Instagram
          IG_PAGE_ACCESS_TOKEN: ${{ secrets.IG_PAGE_ACCESS_TOKEN }}
          IG_BUSINESS_ID: ${{ secrets.IG_BUSINESS_ID }}
          IG_USER_ACCESS_TOKEN: ${{ secrets.IG_USER_ACCESS_TOKEN }}
          PAGE_ID: ${{ secrets.PAGE_ID }}
          FB_APP_ID: ${{ secrets.FB_APP_ID }}
          FB_APP_SECRET: ${{ secrets.FB_APP_SECRET }}

          # App config (safe defaults; override with repo Variables)
          TIMEZONE: Asia/Seoul
          SCHOOL_NAME: ${{ vars.SCHOOL_NAME || '선린인터넷고등학교' }}
          SCHOOL_LEVEL: ${{ vars.SCHOOL_LEVEL || 'his' }}
          GRADE: ${{ vars.GRADE || '3' }}
          CLASS_NM: ${{ vars.CLASS_NM || '11' }}
          BRAND_COLOR_HEX: ${{ vars.BRAND_COLOR_HEX || '#2A6CF0' }}

          # Posting mode: default true unless manually overridden
          POST_TEST_MODE: ${{ inputs.test_mode || 'true' }}

          # Placement tuning (optional)
          DATE_ANCHOR_XY: ${{ vars.DATE_ANCHOR_XY }}
          DATE_ANCHOR_MODE: ${{ vars.DATE_ANCHOR_MODE }}
          DATE_ALIGN: ${{ vars.DATE_ALIGN }}
          DATE_ALIGN_X1: ${{ vars.DATE_ALIGN_X1 }}

          SUBJECT_ANCHOR_XY: ${{ vars.SUBJECT_ANCHOR_XY }}
          SUBJECT_ANCHOR_MODE: ${{ vars.SUBJECT_ANCHOR_MODE }}
          SUBJECT_ROW_DY: ${{ vars.SUBJECT_ROW_DY }}
          SUBJECT_ALIGN: ${{ vars.SUBJECT_ALIGN }}
          SUBJECT_ALIGN_X1: ${{ vars.SUBJECT_ALIGN_X1 }}
          SUBJECT_ANCHOR_AFTER_LUNCH_XY: ${{ vars.SUBJECT_ANCHOR_AFTER_LUNCH_XY }}
          SUBJECT_ANCHOR_AFTER_LUNCH_XY_7TIME: ${{ vars.SUBJECT_ANCHOR_AFTER_LUNCH_XY_7TIME }}
          SUBJECT_ROW_DY_AFTER_LUNCH: ${{ vars.SUBJECT_ROW_DY_AFTER_LUNCH }}

        run: |
          python -m src.daemon --run-now
        if: ${{ steps.weekday.outputs.skip != 'true' }}

      - name: Save state cache
        # Run even if earlier step failed, but only on weekdays and when no cache hit
        if: ${{ always() && steps.weekday.outputs.skip != 'true' && steps.state_cache.outputs.cache-hit != 'true' }}
        continue-on-error: true
        uses: actions/cache/save@v4
        with:
          path: state
          key: state-${{ github.ref_name }}-${{ github.run_id }}-${{ github.run_attempt }}

      - name: Upload image artifact
        # Upload regardless of prior failures, but only on weekdays
        if: ${{ always() && steps.weekday.outputs.skip != 'true' }}
        uses: actions/upload-artifact@v4
        with:
          name: timetable-image
          path: out/*.jpg
          if-no-files-found: warn
